version: '3.7'
services:
  backend:
    build:
      dockerfile: ../docker/backend/Dockerfile.prod
    environment:
      DATABASE_PATH: tmp/production.sqlite3
      RAILS_ENV: production
      RAILS_MASTER_KEY: 687247c6720babc12ef69f1c40e423bd

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.prod
    command: yarn start
